version: '3.0'

services:
  postgresql:
    container_name: bdd
    image: postgres:alpine3.17
    restart: always
    environment:
     # - POSTGRES_USER=labyrinthe
      - POSTGRES_PASSWORD=bdd
    ports:
      - "4000:5432"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/create_tables.sql
      - test-volumes:/var/lib/postgresql/data
    networks:
      - backendnetworks
    
  
  backend:
    container_name: serveur
    build: .
    image: serveur
    depends_on:
      - postgresql
    command: sleep 99999
    ports:
      - 3000:88
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: bdd
      DB_NAME: postgres
    links:
      - postgresql
    volumes:
      - ./nodejs/main.js:/labyrinthe/main.js
    networks:
      - backendnetworks
    


networks:
  bdd: {}
  backendnetworks: {}

volumes:
  test-volumes: {}



